# GitGuardian configuration
# https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit#configuration

version: 2

# Paths to exclude from scanning
paths-ignore:
  - "**/*.md"
  - "**/*.example"
  - "**/*.sample"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/.git/**"
  - "**/coverage/**"
  - "docker-compose.yml"
  - "docker-compose.*.yml"

# Secrets to ignore (resolved/false positives)
matches-ignore:
  # Docker Compose development credentials - uses env vars with fallback
  - name: "docker-compose development defaults"
    match: "POSTGRES_PASSWORD:-postgres"

  - name: "docker-compose timescale defaults"
    match: "TIMESCALE_PASSWORD:-postgres"

  - name: "docker-compose pgadmin defaults"
    match: "PGADMIN_PASSWORD:-admin"

  # CI/CD test placeholders
  - name: "test api key in ci"
    match: "OPENWEATHER_API_KEY: test-key"
