# GitGuardian configuration
# https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit#configuration

version: 2

# Paths to exclude from scanning
paths-ignore:
  - "**/*.md"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/.git/**"
  - "**/coverage/**"
  - "**/*.example"
  - "**/*.sample"

# Secrets to ignore (resolved/false positives)
matches-ignore:
  # Generic Password in docker-compose.yml - Development only, not used in production
  - name: "postgres development password"
    match: "POSTGRES_PASSWORD: postgres"

  # OpenWeather API Key in backend-ci.yml - Test placeholder, not a real key
  - name: "test api key in ci"
    match: "OPENWEATHER_API_KEY: test-key"
